[package]
name = "index-pgn"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
pgn-reader = "0.27.0"
rusqlite = { version = "0.36.0" }
shakmaty = "0.28.0"

[features]
# Bundle a version of sqlite with the binary. 
bundled = ["rusqlite/bundled"]
